name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install modules
        run: |
          cd mobile-ui
          npm install
      - name: Run ESLint
        run: |
          cd mobile-ui
          eslint . --ext .js,.jsx,.ts,.tsx
